### ISSUE TITLE
Comment captcha isn't working

### ISSUE THREAD

**Issue by kristinashu** [mozilla/ihr-landing-site#20]
@Solanasaurus noticed the captcha on the commenting plugin doesn't work when the user is not on a mozilla network. 

<img width="426" alt="screen shot 2017-08-10 at 2 53 22 pm" src="https://user-images.githubusercontent.com/1068783/29193799-b3cac312-7ddb-11e7-8e3f-3a4e5dc734fe.png">

@cadecairos could this be a security thing on our end or @mzanni is this an issue with the wordpress plugin?

**Comment by kristinashu** [comment]
The image shows that the captcha I entered isn't the same but that's only because it loaded a new captcha with the error and kept what I had previously entered!

**Comment by Solanasaurus** [comment]
I just want to emphasize that this is urgent since people aren't able to comment event though we ask them for feedback! The comments worked on v.01 but have had the same problem more than once. Resetting the captcha settings in the plugin isn't working as I thought it did the previous time.

PHP problem or something else? That's what Google suggested. Help!

**Comment by cadecairos** [comment]
OK I think I got it working, can you confirm?

I switched the "captcha generation type" to "use file system" and purged all the caches.

**Comment by Solanasaurus** [comment]
Hallelujah it works, now it says my comment is awaiting moderation. Thanks Chris! I don’t understand why the caches would make a difference?

**Comment by cadecairos** [comment]
WPDiscuz probably injects client side scripts into our pages, so if we change settings on the dashboard, we need to purge the CDN caches so that changes can be reflected in peoples web browsers.

**Comment by kristinashu** [comment]
It's also now working for me! Thank you!
