### ISSUE TITLE
The Feedback form (iframe) displays an error on the blog website

### ISSUE THREAD

**Issue by kaodro** [mozilla/ihr-landing-site#24]
See:
https://internethealthreport.org/feedback/

[screen shot 2017-11-30 at 6 37 32 pm](https://user-images.githubusercontent.com/22129061/33445604-9c86656a-d5fd-11e7-816d-f294acc55d59.png)

@cadecairos

**Comment by cadecairos** [comment]
@kaodro Wasn't this resource created for us by someone on the Coral Project? Have they accidentally deleted it?

This bucket did indeed not exist anymore, and I've gone ahead and created it so that we're not vulnerable to getting taken over by a bad actor. Not sure what to put in its place... The error should now say access denied.

**Comment by alanmoo** [comment]
Should we take the feedback link out of the nav for the time being so it doesn't show an error?

**Comment by cadecairos** [comment]
I've commented out the embed, and added "Feedback has been  temporarily disabled" to the page.

**Comment by kaodro** [comment]
Thanks @cadecairos and @alanmoo 
@jtnelson was our contact regarding the Coral form - Jeff, can you help or advice here on what happened? Thanks!
