### ISSUE TITLE
Review and add content to site

### ISSUE THREAD

**Issue by kristinashu** [mozilla/ihr-landing-site#3]
@samanthaburton @Solanasaurus @kaodro exciting news! @cadecairos and @mzanni have the site up on staging https://healthreport.staging.wpengine.com/

It is ready for you to review. While reviewing the site, please keep in mind I've already given [some feedback](https://github.com/mozilla/ihr-landing-site/issues/2) which Mike is working on now. I'm also working on a more thorough [quality assurance checklist](https://github.com/mozilla/ihr-landing-site/issues/1) to review with site.

I believe the site is ready for all of you to add real content to. @cadecairos please confirm that it's ok for them to add content and if so, please add them to the wordpress account?

Yay!

**Comment by cadecairos** [comment]
Yes we can add content to the new site.

**Comment by kaodro** [comment]
Great!!
We will review the website soon and then I will start adding content. Namely: 

1) Existing blogposts:
How would you measure the health of the Internet? 
What you said about Mozilla’s Internet Health Report 
Step into the “Internet Health Clinic” @ re:publica 17
Digital Citizens, Let’s Talk About Internet Health 
2) Deep dive: Voice Enabled Internet (forthcoming in August)
3) And the Indicators are... (forthcoming in August)
4) Translations: I will explore the opportunity of translating all the content into French, German and Spanish with our possible translation provider (GV) so if that works out timewise, we would start entering translations for the existing blogposts and the UI in the next two weeks. Is the translation plugin also operational? @cadecairos

**Comment by cadecairos** [comment]
I've sent @samanthaburton and @kaodro invites to the new blog on the network. @solanasaurus is already a network admin and can access the site. (remember, it's on the staging site, which is a copy of production, so credentials and such are all the same.

**Comment by cadecairos** [comment]
> Translations: I will explore the opportunity of translating all the content into French, German and Spanish with our possible translation provider (GV) so if that works out timewise, we would start entering translations for the existing blogposts and the UI in the next two weeks. Is the translation plugin also operational? @cadecairos

This is tricky - have we done any translations on production in the last three weeks? If we translate on staging, I'll have to overwrite the translations tables in the production database when we push the new site to production, and this will overwrite all changes made there.

**Comment by kaodro** [comment]
Afaik we didn't do any translations in the last 3 weeks. What do you suggest to make it less tricky? Would pushing the new site to production first and adding the translations later (directly in production?) help?

**Comment by cadecairos** [comment]
That depends on if we need to make changes to production before we push the new site out. If we don't make any changes, we can leave things as they are right now and safely deploy it when the time comes.

(The reason this is an issue is because both sites share database tables for their translations, while the sites themselves don't share database tables, so we can push the new site without affecting the existing one)

**Comment by Solanasaurus** [comment]
I believe the German About page on the production site is more recent than the one on staging (some grammar changes). That's an example of something we would have to bring in line before we push any translations from staging, correct? I think there are only a couple of other things.

I'm surprised the translation database is connected across all sites!

**Comment by kaodro** [comment]
FYI, the content to be added to the site is here: https://docs.google.com/document/d/13m7VdEtDs80rNn6_U07nPsn4iN7zC3rBPvM6O1OkR8o/edit. Once I start adding tomorrow I will mark how far I came.

**Comment by samanthaburton** [comment]
Hi folks! Thanks for the great work on this site, it's looking fantastic. Just a few small comments from my side:

- [ ] On the landing page, the link to the Internet Health Report v0.1 (both the image & 'read more' graphic) is broken. I'm not sure if this is a bug, or if it just hasn't been added yet!
- [ ] On the blog page, the list of categories is a bit hard to read -- would we be able to organize them so they're easier to digest?
![screen shot 2017-07-12 at 4 37 08 pm](https://user-images.githubusercontent.com/16709293/28138912-68d2ad2e-6720-11e7-9ae9-e087e155410b.png)
- [ ] On About page, email for Solana is currently a test - I think this should direct you to internethealth@mozillafoundation.org? @Solanasaurus thoughts?

That's all from me for now - please let me know if there's anything else you want me to have a look at. Thanks so much again!

**Comment by kristinashu** [comment]
Excellent! The first two are already filed in https://github.com/mozilla/ihr-landing-site/issues/4 and the third one can easily be updated through the WP admin!

**Comment by samanthaburton** [comment]
//facepalm// Sorry I missed them there! But yay for all the bases being covered? :)

**Comment by kristinashu** [comment]
@kaodro I've update/added all the content from that word doc. You will just need to add the correct Tags + Categories to the blog posts and updates based on Sam's comments in the word doc.

**Comment by kaodro** [comment]
@kristinashu wow, that was fast (I shouldn't have raised this issue at all, bad time estimation), thanks so much for doing this! I will finish it up tomorrow and will also add my review if I find any bugs.

**Comment by kaodro** [comment]
@kristinashu @Solanasaurus Here is what I did:

1) I added tags (we discussed with Solana and introduced a generic tag "internet health" for generic articles). The categories issue @samanthaburton reported seems resolved: we only have 3 categories and the other (internet issues names) are tags that serve us internally to filter posts but do not appear on the website. I also renamed "Uncategorized" into "Project Updates" so that this is the default category and the ugly "Uncategorized" doesn't appear on the website (@kristina, you can resolve this one bug reported in #4 ). I also wrote all category names with capital letter as I wasn't able to change "Most recent" into small letter and it looked inconsistent (also the big categories on the top of the page are written with capital letters).
2) I implemented changes suggested by Sam in the google doc
3) I replaced the test email with Solana's email on the about page
4) I added "This post was originally published on XXX" at the end of each blogpost
5) I updated the published dates so they match the original dates 
6) I replaced the description of the Deep Dive with the Indicators as the link (which is broken, but that is already reported) should lead to the Indicators discussion on consider.it and the image also fits the indicators more than Voice enabled Internet. Deep Dive will not be ready until 2nd week of August so with Indicators we are featuring sth that already exists. Related to that: I removed the blogpost about indicators from featured blogpost to avoid duplication.
7) I changed the translation language from Dutch to German (Deutsch :)

Here are the bugs/things we would like to change @kristinashu :

1) We would like to change the teaser image on the homepage for the Report v0.1 into something matching the colors of the report 
2) The teaser image for the featured post about the Clinic is cut in half and looks weird
3) Images with captions have a weird white space around them (on the top and bottom, https://healthreport.staging.wpengine.com/2017/01/19/digital-citizens-lets-talk-about-internet-health/), and an outline around them. We would like to remove the outline and the white space and leave only as much white space as needed for the caption.
4) Did we make sure we are in line with accessibility standards (w3c)?

Apart from that all looks great and works great, a huge thanks to all who made that happen, @kristinashu, Mike and @cadecairos!

**Comment by kaodro** [comment]
@cadecairos Related to the translation issue: I remembered now that I actually made changes to translated versions 6 days ago (you can see it in the "simple history" plugin) in production but they were very minor (I updated links) so I could do them to staging to. Would that help the situation for now? (I am planning to work with translators in the next 3 weeks and would like them to work directly in wordpress to test the process for the future).

We were thinking about the solution to that common database issue and came up with following questions/maybe solution proposals:

1) Can you section off what you push to production from translation side? Just specific articles/website or does it always have to be the entire thing? We assume so but wanted to make sure.  

2) Solution 1: for the Report 1.0. we would never translate anything on staging and always on password-protected production. 
3) Solution 2: we always translate on Staging and never on production = that makes us dependent on developer to do the push to production for each change
4) Solution 3: each time you want to push sth from staging, you could copy the production content to staging first, then add new stuff and and push it again to production. That would allow us to do small changes directly in production. Sounds very cumbersome, though.

Is there a tracking system to track and compare changes made to production and staging?

Thanks!

**Comment by kristinashu** [comment]
Excellent @kaodro! Here's some follow up:

> 1) I added tags (we discussed with Solana and introduced a generic tag "internet health" for generic articles). The categories issue @samanthaburton reported seems resolved: we only have 3 categories and the other (internet issues names) are tags that serve us internally to filter posts but do not appear on the website. I also renamed "Uncategorized" into "Project Updates" so that this is the default category and the ugly "Uncategorized" doesn't appear on the website (@kristina, you can resolve this one bug reported in #4 ). I also wrote all category names with capital letter as I wasn't able to change "Most recent" into small letter and it looked inconsistent (also the big categories on the top of the page are written with capital letters).

Update in the bug ticket https://github.com/mozilla/ihr-landing-site/issues/4#issuecomment-314859809

> 1) We would like to change the teaser image on the homepage for the Report v0.1 into something matching the colors of the report 

Opened a design ticket for this #5

> 2) The teaser image for the featured post about the Clinic is cut in half and looks weird

This is filed here https://github.com/mozilla/ihr-landing-site/issues/4#issuecomment-314880104

> 3) Images with captions have a weird white space around them (on the top and bottom, https://healthreport.staging.wpengine.com/2017/01/19/digital-citizens-lets-talk-about-internet-health/), and an outline around them. We would like to remove the outline and the white space and leave only as much white space as needed for the caption.

This is filed here https://github.com/mozilla/ihr-landing-site/issues/4#issuecomment-315141706

> 4) Did we make sure we are in line with accessibility standards (w3c)?

This is part of the QA checklist https://github.com/mozilla/ihr-landing-site/issues/1

**Comment by kristinashu** [comment]
Thank you everyone for the feedback and content! 

Mike will be working on the finishing touches in https://github.com/mozilla/ihr-landing-site/issues/2 and https://github.com/mozilla/ihr-landing-site/issues/4

The only outstanding issue in this ticket is around the translations, so I've opened a [dedicated ticket](https://github.com/mozilla/ihr-landing-site/issues/7).

Also noting that we are finalizing launch plan [here](https://github.com/MozillaFoundation/mofo-devops/issues/519#issuecomment-315171020).
